### ISSUE TITLE
Got error when publishing the component

### ISSUE THREAD

**Issue by zenepay** [BJNSTNKVC/laravel-mail-components#4]
Laravel 11,
php 8.2

php artisan components:publish
```php

 Illuminate\Contracts\Filesystem\FileNotFoundException 

  File does not exist at path /home/zenclub/hrm/vendor/bjnstnkvc/mail-components/src/Helpers\..\View\Components\Mail\Button.php.

  at vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:58
     54▕         if ($this->isFile($path)) {
     55▕             return $lock ? $this->sharedGet($path) : file_get_contents($path);
     56▕         }
     57▕
  ➜  58▕         throw new FileNotFoundException("File does not exist at path {$path}.");
     59▕     }
     60▕
     61▕     /**
     62▕      * Get the contents of a file as decoded JSON.

```
      +14 vendor frames

**Comment by BJNSTNKVC** [comment]
First of all, thank you for using the package, as well as for creating an issue. 

Unfortunately, I am unable to reproduce the issue. The environment I used to test it is:

- Windows 11
- PHP 8.2.18
- Laravel 11.29.0
- bjnstnkvc/mail-components 1.1.4


If you haven't already, try updating the package to the latest version via `composer update`. Additionally, have you by any chance published the package config, and if so, can you share the contents?

**Comment by Aliyan-12** [comment]
Hey buddy, the issue seems familiar to me as I also got the same issue while sending emails in my laravel project. You can follow this guide to fix the issue: [https://packagist.org/packages/bjnstnkvc/mail-components](url). I fixed it by reinstalling the package.

Also as the error is about the illuminate/filesystem so you can check if your current version of **bjnstnkvc/mail-components:1.1.4** is compatible with the **illuminate/filesystem** package.
![issue](https://github.com/user-attachments/assets/eafc2b84-491c-4165-8a8b-d06971da3d74)

Maybe this helps :)
